version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: agora-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: eventbooking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: fahrinizar/agora-eventbooking:v1
    container_name: agora-api
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_URL=jdbc:postgresql://db:5432/eventbooking

volumes:
  postgres_data: